version: '3.4'

services:
  scraper:
    image: scraper
    build:
      context: .
      dockerfile: ./Dockerfile
    cap_add:
      - SYS_ADMIN
    environment:
      NODE_ENV: production
      NORDNET_USERNAME: ${NORDNET_USERNAME}
      NORDNET_PASSWORD: ${NORDNET_PASSWORD}
    ports:
      - 3000:3000
